### ISSUE TITLE
Allow to select other POIs while one is already selected

### ISSUE THREAD

**Issue by maciejla** [headwaymaps/headway#177]
Currently, if you select one POI, you have to click the `x` button in the search bar in order to select another POI. It would be nice to have the ability to just select another POI, without resetting it with the `x`

**Comment by ellenhp** [comment]
Does this occur in latest `main`? I think you're running into #166 which has been fixed, just not deployed yet to the demo installation.

**Comment by maciejla** [comment]
I tested it only on the demo installation, this seems to be a duplicate of #166. Sorry for bothering you :)

**Comment by maciejla** [comment]
Duplicate of #166

**Comment by maciejla** [comment]
Unfortunately, this still doesn't work on main :( here's a video to help understand what I mean. As you can see, it's not possible to select another POI while one was already selected

https://user-images.githubusercontent.com/85807099/195152865-8fb6f273-b262-40ef-aff7-c591d0fa6987.mp4

**Comment by michaelkirk** [comment]
This should be fixed now. Please let me know if you can continue to reproduce it.

**Comment by maciejla** [comment]
Fixed! Thank you!
